[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/game_object.lua"]'
pattern = "if G.GAME.used_vouchers.v_omen_globe and pseudorandom('omen_globe') > 0.8 then"
position = "at"
match_indent = true
payload = '''
if G.GAME.used_vouchers.v_hololive_suit_flower and (i == 1) then
    local _tarot = Holo.roll_for_suit_tarot()
    _card = {set = "Tarot", area = G.pack_cards, skip_materialize = true, soulable = true, key = _tarot, key_append = "ar_flower"}
elseif G.GAME.used_vouchers.v_hololive_mod_book and (i == 1) then
    local _tarot = Holo.roll_for_enhance_tarot()
    _card = {set = "Tarot", area = G.pack_cards, skip_materialize = true, soulable = true, key = _tarot, key_append = "ar_book"}
elseif G.GAME.used_vouchers.v_hololive_suit_flower and G.GAME.used_vouchers.v_hololive_mod_book and (i == 2) then
    local _tarot = Holo.roll_for_enhance_tarot()
    _card = {set = "Tarot", area = G.pack_cards, skip_materialize = true, soulable = true, key = _tarot, key_append = "ar_book"}
elseif G.GAME.used_vouchers.v_omen_globe and pseudorandom('omen_globe') > 0.8 then
'''