[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if card and card.playing_card then SMODS.drawn_cards[#SMODS.drawn_cards+1] = card end"
position = "after"
match_indent = true
payload = '''
if (from==G.deck)and(to==G.hand) then
    SMODS.calculate_context({
        hololive_drawn_card = card,
    })
end
if (from==G.hand)and(to==G.play) then
    -- What's the difference between this and context.before?
    SMODS.calculate_context({
        hololive_played_card = card,
    })
end
if (from==G.play)and(to==G.discard)then
    SMODS.calculate_context({
        hololive_exited_card = card,
    })
end
'''
